# Generated by Django 5.0.4 on 2024-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='return_id',
            field=models.CharField(default=656767, max_length=100),
            preserve_default=False,
        ),
    ]
