# Generated by Django 5.0.4 on 2024-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_uploadedfile_return_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, to='fileupload.attachment')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
