# Generated by Django 5.0.4 on 2024-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_attachment_mymodel_delete_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='file',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='attachments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
