# Generated by Django 5.0.4 on 2024-04-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_remove_mymodel_attachments_remove_mymodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='attachments',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
