# Generated by Django 5.0.4 on 2024-04-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0006_alter_mymodel_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='return_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
