# Generated by Django 5.0.4 on 2024-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0007_alter_mymodel_return_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.IntegerField()),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
