# Generated by Django 5.0.4 on 2024-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_multiplefileupload_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplefileupload',
            name='attachments',
            field=models.JSONField(default=[]),
        ),
    ]
