# Generated by Django 5.0.4 on 2024-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0009_alter_multiplefileupload_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplefileupload',
            name='attachments',
            field=models.JSONField(default=dict),
        ),
    ]
