# Generated by Django 5.0.4 on 2024-04-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0012_alter_bednightreturn_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleFileUpload',
        ),
        migrations.AlterField(
            model_name='bednightreturn',
            name='return_master',
            field=models.PositiveIntegerField(db_column='return_id'),
        ),
    ]
