# Generated by Django 5.0.4 on 2024-04-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0013_delete_multiplefileupload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bednightreturn',
            name='number_of_facility',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
