# Generated by Django 5.0.4 on 2024-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0014_alter_bednightreturn_number_of_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bednightreturn',
            name='number_of_facility',
            field=models.PositiveIntegerField(),
        ),
    ]
