# Generated by Django 5.0.4 on 2024-04-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiableToFileReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
            ],
        ),
    ]
