# Generated by Django 5.0.4 on 2024-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0002_liabletofilereturn1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='STATUS',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
