# Generated by Django 5.0.4 on 2024-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0003_alter_liabletofilereturn_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='tin',
            field=models.BigIntegerField(max_length=10, unique=True),
        ),
    ]
