# Generated by Django 5.0.4 on 2024-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0004_alter_liabletofilereturn_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabletofilereturn',
            name='return_type',
            field=models.CharField(db_column='RETUEN_TYPE', default=78, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='business',
            field=models.CharField(db_column='BUSNESS', max_length=100),
        ),
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='name',
            field=models.CharField(db_column='NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='tin',
            field=models.BigIntegerField(db_column='TIN', max_length=10, unique=True),
        ),
    ]
