# Generated by Django 5.0.4 on 2024-04-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0005_liabletofilereturn_return_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='business',
            field=models.CharField(db_column='BUSINESS', max_length=100),
        ),
        migrations.AlterField(
            model_name='liabletofilereturn',
            name='tin',
            field=models.BigIntegerField(db_column='TIN', unique=True),
        ),
    ]
