# Generated by Django 5.0.4 on 2024-04-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exceldata', '0006_alter_liabletofilereturn_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabletofilereturn',
            name='status',
            field=models.CharField(choices=[('UPD', 'Uploaded'), ('RVD', 'Reviwed'), ('APD', 'Approved')], default='APD', max_length=3),
        ),
    ]
