@host_dev = http://127.0.0.1:8000/returns/


GET {{host_dev}}monthly/
Accept: application/json


###
GET {{host_dev}}monthly/?taxpayer_id=123456789&month=11&year=2024&category=141
Content-Type: application/json

###
POST {{host_dev}}monthly/?taxpayer_id=123456789&start_month=2&category=108
Content-Type: application/json

###
PATCH {{host_dev}}monthly/?status=3
Content-Type: application/json

[
    {
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 2,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 3,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 4,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 5,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 6,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 7,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 8,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 9,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 10,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 11,
        "year": 2024
    },{
        "taxpayer_id": 123456789,
        "category": 141,
        "month": 12,
        "year": 2024
    }
]